### PR TITLE
[Chore] Update xrefcheck to v0.2.2

### PR DESCRIPTION
**Pull request by Sorokin-Anton**
## Description
Update xrefcheck to v0.2.2. Also switch GitHub actions to newer versions.

## Related issue(s)

None

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/main/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/main/docs/code-style.md).

### CODE REVIEW

**Comment by Sorokin-Anton** [comment]
@dcastro some CI checks (e.g. CI / stack / ghc 9.0.2 (pull_request) ) fails with message 
```

file "./tztime.cabal" has changed
3c3
< -- This file has been generated from package.yaml by hpack version 0.34.4.
---
> -- This file has been generated from package.yaml by hpack version 0.35.0.
109a110
>   default-language: Haskell2010
112d112
<   default-language: Haskell2010
177a178
>   default-language: Haskell2010
180d180
<   default-language: Haskell2010
260a261
>   default-language: Haskell2010
263d263
<   default-language: Haskell2010
run ./scripts/generate-cabal-files.sh locally
and update cabal related fiels
```

I haven't change any of those and if I run `./scripts/generate-cabal-files.sh` loaclly, there is no diff. Maybe you encountered something like this?

UPD: stack build generated other files, but they aren't working too

**Comment by dcastro** [comment]
Ok, so the issue seems to be the following. The `Validate cabal files` step runs these commands:

```
stack install stack2cabal --resolver snapshot-stack2cabal.yaml --system-ghc
./scripts/validate-cabal-files.sh
```

The first command runs some version of `stack` that apparently uses hpack 0.35.0. So, while the first command is running, the stack files are modified:

```diff
- -- This file has been generated from package.yaml by hpack version 0.34.4.
+ -- This file has been generated from package.yaml by hpack version 0.35.0.
```

Then we run `./scripts/validate-cabal-files.sh`, which runs `stack2cabal`, which we just built with hpack 0.34.4, and expects the cabal file to say it was built with hpack 0.34.4 - which fails.

-------

One solution would be to run `git checkout -- . ` in-between the 2 commands.

A better solution would be to modify `snapshot-stack2cabal.yaml` such that it builds stack2cabal using hpack-0.35.0.

```yaml
packages:
  # The version of hpack must match the version of hpack
  # bundled with the version of `stack` we're using in `.github/workflows/ci.yml`
  - hpack-0.35.0
```

---

One mystery remains: In `ci.yml`, we're stating we want to use `stack: ["2.7.5"]`. However, I'm pretty sure stack 2.7.5 does NOT use hpack 0.35.0. [The release notes](https://docs.haskellstack.org/en/stable/ChangeLog/#v291-2022-09-19) say hpack was bumped to 0.35.0 only when stack 2.9.1 was released.

So how come the first command in the CI is using hpack 0.35.0? Is it for some reason using stack 2.9.1 instead of 2.7.5?

Can you please add `stack --version` to the "Validate cabal files" CI step so we can see what's going on?

**Comment by Sorokin-Anton** [comment]
> A better solution would be to modify snapshot-stack2cabal.yaml such that it builds stack2cabal using hpack-0.35.0.

So now 8.10.7 failed with even stranger message (O_o):
```
  Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
  /home/runner/.ghcup/bin/cabal update
  Error: cabal: Cannot find the program 'ghc'. User-specified path 'ghc-9.0.2'
  does not refer to an executable and the program is not on the system path.
```

UPD: oh, it's related to haskell/actions/setup@v2 , not to hpack

**Comment by dcastro** [comment]
[The logs say](https://github.com/serokell/tztime/actions/runs/3345189148/jobs/5540403365#step:7:7):

> Version 2.[7](https://github.com/serokell/tztime/actions/runs/3345189148/jobs/5540403365#step:7:8).5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4

So my hypothesis is out the window :sweat_smile: 

Anyways, it's working now! :tada: 

Please add that comment I left above to `snapshot-stack2cabal.yaml` explaining that the hpack versions must match

**Review by dcastro — APPROVED** [review]

**Pull request merged**
